# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(max_length=18, verbose_name='MAC Address')),
            ],
        ),
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap', models.ManyToManyField(to='map.AccessPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('lat', 'lng')]),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Location'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Location'),
        ),
    ]
