# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedicatedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, null=True, unique=True, verbose_name='MAC Address')),
            ],
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='direction',
            field=models.CharField(choices=[('north', 'North'), ('east', 'East'), ('west', 'West'), ('south', 'South')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.DedicatedGroup'),
        ),
    ]
