# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerprint',
            old_name='ap',
            new_name='access_point',
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='rssi',
            field=models.IntegerField(null=True),
        ),
    ]
