# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170404_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprint',
            name='access_point',
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='access_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.AccessPoint'),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Location'),
        ),
    ]
