# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170405_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='bssid',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='MAC Address'),
        ),
    ]
